# permissions for end users to edit rayjobs.
{{- if and .Values.rbacEnable (not .Values.singleNamespaceInstall) }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rayjob-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - ray.io
  resources:
  - rayjobs
  - rayjobs/status
  verbs:
  - get
  - list
  - watch
{{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rayjob-editor-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - ray.io
  resources:
  - rayjobs
  verbs:
  - create
  - delete
  - patch
  - update
  - deletecollection
{{- end }}
